/**
 * Provenance badge (STEP 5) — makes it impossible to mistake a local-model
 * answer for a remote one. Every AI surface in the app renders this next to
 * the response it came from.
 */

import type { AiProvenance } from "@/lib/offline/local-engine";

export function ProvenanceBadge({ provenance }: { provenance: AiProvenance }) {
  const local = provenance.origin === "local";
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-medium ${
        local ? "bg-amber-100 text-amber-900" : "bg-blue-100 text-blue-900"
      }`}
      title={local ? "Generated on this device by a small local model — no network used" : "Generated by the remote model over the network"}
    >
      {local ? "LOCAL MODEL" : "REMOTE MODEL"}
      <span className="opacity-60">· {provenance.model}</span>
      {typeof provenance.latencyMs === "number" && <span className="opacity-60">· {provenance.latencyMs} ms</span>}
    </span>
  );
}
